version: 2

models:
  - name: int_clientes
    description: "Tabela intermediária consolidando dados de clientes e compras."
    columns:
      - name: customer_id
        description: "Identificador único do cliente."
      - name: customer_name
        description: "Nome completo do cliente."
      - name: customer_address
        description: "Endereço do cliente."
      - name: customer_phone
        description: "Número de telefone do cliente."
      - name: customer_email
        description: "E-mail do cliente."
      - name: total_gasto
        description: "Total gasto pelo cliente."
      - name: total_compras
        description: "Número total de compras realizadas pelo cliente."

  - name: int_produtos
    description: "Tabela intermediária consolidando dados de produtos e vendas."
    columns:
      - name: product_id
        description: "Identificador único do produto."
      - name: name_product
        description: "Nome do produto."
      - name: price_product
        description: "Preço do produto."
      - name: total_vendido
        description: "Quantidade total vendida do produto."
      - name: total_faturado
        description: "Valor total faturado com o produto."

  - name: int_vendas
    description: "Tabela intermediária consolidando vendas e estornos."
    columns:
      - name: purchase_id
        description: "Identificador único da venda."
      - name: customer_id
        description: "Identificador do cliente."
      - name: product_id
        description: "Identificador do produto."
      - name: purchase_date
        description: "Data da compra."
      - name: quantity
        description: "Quantidade de produtos comprados."
      - name: total_price
        description: "Preço total da compra."
      - name: payment_method
        description: "Método de pagamento utilizado."
      - name: valor_estornado
        description: "Valor estornado na compra."
      - name: refund_reason
        description: "Motivo do estorno, caso tenha ocorrido."

  - name: int_estorno  
    description: "Registros de estornos com informações de cliente, produto, data e motivo"
    columns:
      - name: purchase_id
        description: "Identificador da compra estornada"

      - name: customer_id
        description: "Identificador do cliente"

      - name: product_id
        description: "Identificador do produto estornado"


      - name: refund_date
        description: "Data do estorno"

      - name: refund_reason
        description: "Motivo do estorno"


      - name: refund_amount
        description: "Valor reembolsado"