version: 2

models:
  - name: fct_vendas
    description: "Tabela fato de vendas com informações de clientes, produtos e estornos"
    columns:
      - name: purchase_id
        description: "Identificador único da compra"
      - name: customer_id
        description: "Identificador do cliente"
      - name: customer_name
        description: "Nome do cliente"
      - name: customer_email
        description: "Email do cliente"
      - name: product_id
        description: "Identificador do produto"
      - name: name_product
        description: "Nome do produto"
      - name: purchase_date
        description: "Data da compra"
      - name: quantity
        description: "Quantidade comprada"
      - name: total_price
        description: "Valor total da compra"
      - name: payment_method
        description: "Forma de pagamento utilizada"
      - name: valor_estornado
        description: "Valor estornado (se houver)"
      - name: refund_reason
        description: "Motivo do estorno"
      - name: receita_liquida
        description: "Valor líquido da venda após estorno"