version: 2

macros:
  - name: generate_schema_name
    description: "{{ doc ('generate_schema_name') }}"
    arguments:
      - name: custom_schema_name
        type: string
        description: "Nome do schema a ser utilizado. Se não for fornecido, será usado o schema do modelo."
      - name: node
        type: object
        description: "Representa o nó do modelo dentro do dbt, contendo metadados como schema e nome do modelo."